#!/usr/bin/env python3
"""
make_fonts.py - subsets the two OFL fonts to Latin and inlines them as base64
into web/fonts.css, so the page renders identically offline, over file://, and
inside the headless renderer with no font fallback surprises.
"""
import base64
import os
import subprocess

FACES = [('Baloo2', 'assets/fonts/Baloo2-ExtraBold.ttf', 800),
         ('Fredoka', 'assets/fonts/Fredoka-Bold.ttf', 700)]

def main():
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    css = ['/* fonts.css - generated by render/make_fonts.py from assets/fonts/*.ttf',
           '   Baloo 2 and Fredoka, SIL Open Font License 1.1 (see assets/fonts/OFL.txt).',
           '   Subset to Latin + punctuation and inlined so the page renders identically',
           '   offline, over file://, and inside the headless renderer. */']
    for name, path, weight in FACES:
        sub = path.replace('.ttf', '.subset.woff2')
        subprocess.run(['pyftsubset', path, '--output-file=' + sub, '--flavor=woff2',
                        '--unicodes=U+0020-007E,U+00A0,U+2018-201D,U+2026',
                        '--layout-features=kern,liga,calt'], check=True)
        b = base64.b64encode(open(sub, 'rb').read()).decode()
        os.remove(sub)
        css.append("@font-face{font-family:'%s';font-style:normal;font-weight:%d;"
                   "font-display:block;src:url(data:font/woff2;base64,%s) format('woff2');}"
                   % (name, weight, b))
    open('web/fonts.css', 'w').write('\n'.join(css) + '\n')
    print('wrote web/fonts.css (%.1f KB)' % (os.path.getsize('web/fonts.css') / 1024))

if __name__ == '__main__':
    main()
