"""Flatten a contract and its imports into one file.

Remix resolves npm imports on its own most of the time, but "most of the
time" is a bad property for the step where you paste a contract that will
hold other people's money. A single self-contained file removes the
question: what you paste is exactly what compiles.
"""
from __future__ import annotations

import os
import re
import sys

CPU_TOKEN_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTRACTS_DIR = os.path.join(CPU_TOKEN_DIR, "contracts")

IMPORT_RE = re.compile(r'^\s*import\s+(?:\{[^}]*\}\s+from\s+)?"([^"]+)"\s*;\s*$', re.M)
SPDX_RE = re.compile(r'^\s*//\s*SPDX-License-Identifier:.*$', re.M)
PRAGMA_RE = re.compile(r'^\s*pragma\s+solidity[^;]*;\s*$', re.M)


def resolve(path: str, node_modules: str, base: str) -> str:
    if path.startswith("."):
        return os.path.normpath(os.path.join(base, path))
    return os.path.join(node_modules, path)


def flatten(entry: str, node_modules: str, seen: set | None = None) -> list[str]:
    """Depth-first so every dependency is defined before whatever uses it."""
    seen = seen if seen is not None else set()
    entry = os.path.normpath(entry)
    if entry in seen:
        return []
    seen.add(entry)

    with open(entry) as fh:
        source = fh.read()

    chunks: list[str] = []
    for imported in IMPORT_RE.findall(source):
        chunks += flatten(resolve(imported, node_modules, os.path.dirname(entry)), node_modules, seen)

    body = IMPORT_RE.sub("", source)
    body = SPDX_RE.sub("", body)
    body = PRAGMA_RE.sub("", body)
    label = os.path.relpath(entry, node_modules) if node_modules in entry else os.path.basename(entry)
    chunks.append(f"// ---- {label} ----\n{body.strip()}\n")
    return chunks


def main(argv=None) -> int:
    argv = argv or sys.argv[1:]
    if len(argv) < 2:
        print("usage: flatten.py <node_modules> <Contract.sol> [more...]", file=sys.stderr)
        return 2
    node_modules, names = argv[0], argv[1:]
    out_dir = os.path.join(CONTRACTS_DIR, "flattened")
    os.makedirs(out_dir, exist_ok=True)

    for name in names:
        chunks = flatten(os.path.join(CONTRACTS_DIR, name), node_modules)
        header = (
            "// SPDX-License-Identifier: MIT\n"
            "pragma solidity 0.8.24;\n\n"
            f"// {name}, flattened with its OpenZeppelin dependencies so it can be\n"
            "// pasted into Remix or a block explorer as a single file.\n"
            "// Generated by cpu_token/scripts/flatten.py — edit the originals, not this.\n\n"
        )
        out = os.path.join(out_dir, name)
        with open(out, "w") as fh:
            fh.write(header + "\n".join(chunks))
        print(f"  {os.path.relpath(out, os.path.dirname(CPU_TOKEN_DIR))}"
              f"  ({len(header) + sum(map(len, chunks)) // 1} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
